apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend
  namespace: taskflow
spec:
  type: ClusterIP
  selector:
    app: taskflow
    component: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
