apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend
  namespace: taskflow
spec:
  type: NodePort
  selector:
    app: taskflow
    component: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
