apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  DB_HOST: "taskflow-postgres"
  DB_PORT: "5432"
  DB_NAME: "taskflow"
  PORT: "4000"
  NODE_ENV: "production"
